"""Initial schema

Revision ID: a34cb10e4c93
Revises: 
Create Date: 2025-11-15 12:43:30.098982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34cb10e4c93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Criar tabelas sem foreign keys primeiro para resolver dependência circular
    
    # 1. Criar tabela files (sem FK para analyses inicialmente)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('original', 'report', 'clean_video', name='filetype'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('cdn_url', sa.String(), nullable=True),
    sa.Column('cdn_uploaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 2. Criar tabela analyses (sem FKs para files inicialmente)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploading', 'analyzing', 'cleaning', 'completed', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('original_file_id', sa.UUID(), nullable=False),
    sa.Column('report_file_id', sa.UUID(), nullable=True),
    sa.Column('clean_video_id', sa.UUID(), nullable=True),
    sa.Column('video_metadata', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 3. Criar tabela analysis_steps (sem FK para analyses inicialmente)
    op.create_table('analysis_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.Enum('upload', 'metadata_extraction', 'prnu', 'fft', 'classification', 'cleaning', 'cdn_upload', name='stepname'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='stepstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('step_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 4. Adicionar foreign keys após todas as tabelas existirem
    # FK de files para analyses
    op.create_foreign_key(
        'fk_files_analysis_id',
        'files', 'analyses',
        ['analysis_id'], ['id']
    )
    
    # FKs de analyses para files
    op.create_foreign_key(
        'fk_analyses_original_file_id',
        'analyses', 'files',
        ['original_file_id'], ['id']
    )
    op.create_foreign_key(
        'fk_analyses_report_file_id',
        'analyses', 'files',
        ['report_file_id'], ['id']
    )
    op.create_foreign_key(
        'fk_analyses_clean_video_id',
        'analyses', 'files',
        ['clean_video_id'], ['id']
    )
    
    # FK de analysis_steps para analyses
    op.create_foreign_key(
        'fk_analysis_steps_analysis_id',
        'analysis_steps', 'analyses',
        ['analysis_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover foreign keys antes de dropar tabelas
    op.drop_constraint('fk_analysis_steps_analysis_id', 'analysis_steps', type_='foreignkey')
    op.drop_constraint('fk_analyses_clean_video_id', 'analyses', type_='foreignkey')
    op.drop_constraint('fk_analyses_report_file_id', 'analyses', type_='foreignkey')
    op.drop_constraint('fk_analyses_original_file_id', 'analyses', type_='foreignkey')
    op.drop_constraint('fk_files_analysis_id', 'files', type_='foreignkey')
    
    # Dropar tabelas na ordem reversa
    op.drop_table('analysis_steps')
    op.drop_table('analyses')
    op.drop_table('files')
    # ### end Alembic commands ###

